Autohr: Balakrishna Chuppala

1.Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [34]:
def Vandermonde(M,N):
    return np.column_stack(tuple(M**(N-i-1) for i in range(N)))

input_vector=np.array([2, 3, 4,5])
no_of_columns=int(input('Enter # columns in output: '))

print('OutPut: \n',Vandermonde(input_vector,no_of_columns))


Enter # columns in output: 5
OutPut: 
 [[ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


2. Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [79]:
data=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [80]:
data

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [82]:
window_size=int(input('Enter Window size for moving avg :'))

Enter Window size for moving avg :3


In [86]:
def Moving_average(x,k):
    Global_MA=[]
    for i in range(0,len(x)-k+1):
        reset_list=[]
#        for j in range(k):
        reset_list.append(np.average(x[i:k+i]))
        Global_MA.append(np.average(reset_list))
    return Global_MA
    
    
print("Moving avg for the data: \n ", np.row_stack(Moving_average(data,window_size)))

Moving avg for the data: 
  [[  5.        ]
 [  4.66666667]
 [  5.66666667]
 [  6.66666667]
 [  9.66666667]
 [ 28.66666667]
 [ 49.33333333]
 [ 72.66666667]
 [ 84.        ]
 [ 93.33333333]
 [116.33333333]]
